- name: run terraform script to create all resources needed
  hosts: localhost
  tasks:
    - name: run terraform script
      terraform:
        project_path: '~/TheQuest/terraform'


- name: wait for azure and refresh inventory with the new groups        
  hosts: localhost
  tasks:
    - pause:
        minutes: 1
    - meta: refresh_inventory


- name: Install and setup nodejs and forever
  hosts: tag_os_ubuntu 
  remote_user: TheQuest
  become: yes
  tasks: 
    - name: Add PPA for LTS Nodejs
      shell: curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
      args:
        warn: no
    - name: Install Nodejs
      apt:
        name: nodejs
        state: latest
    - name: Install Forever
      command: npm install forever -g


- name: Move node files and start the file w/ forever
  hosts: tag_os_ubuntu
  remote_user: TheQuest
  become: yes #don't think this is needed, but maybe because of execution permissions
  tasks:
    - name: Check directory
      stat:
        path: /sw/nodejs/
      register: my_folder
    - name: alert if directrory already existed
      debug:
        msg: "The NodeJS directory already exists!"
      when: my_folder.stat.exists
    - name: Create folder if it doesn't exist
      file:
        path: /sw/nodejs/
        state: directory
        mode: 0755
        group: TheQuest
        owner: TheQuest
      when: my_folder.stat.exists == false
    - name: copy nodejs file to server
      copy:
        src:  ~/TheQuest/nodeFiles/myfirstjs.js
        dest: /sw/nodejs/myfirstjs.js
        owner: root
        group: root
        mode: 0644
    - name: CHedck list of Nodejs apps.
      command: forever list
      register: forever_list
      changed_when: false
    - name: Start application /w Forever
      command: forever start /sw/nodejs/echoArgs.js {{ "node_args" }}
      when: "forever_list.stdout.find('/sw/nodejs/echoArgs.js') ==-1"
